version: '3'

services:

  heresia:
    container_name: heresia
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - gems:/usr/local/bundle
    depends_on:
      - postgres  
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}

  postgres:
    container_name: postgres
    image: postgres:16-bookworm # Cuidado com imagens base alpine
    restart: always
    environment:
      #host do banco visto por dentro do é o nome do serviço por fora e localhost
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  gems:
  data:
